name: CI workflow

# Define when the workflow should be triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to be run
jobs:
  build:
    runs-on: ubuntu-latest

    # Specify the container to use
    container: python:3.9-slim

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Lint with flake8
      - name: Lint with flake8
        run: |
          pip install flake8  # Install flake8 if not already in requirements.txt
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics